name: GitHub build docker

on:
  push:
    branches:
      - master

jobs: 
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true # push to registry
          pull: true # always fetch the latest base images
          tags: ghcr.io/niek/obs-web:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}